title: Shreshth Khilani
email: shreshth.khilani@gmail.com
description: >
  This is the theatre portfolio of Shreshth; 
  he likes to believe that he's a theatre artist and a web developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shreshthkhilani.github.io"
twitter_username: shreshthkhilani
github_username:  shreshthkhilani

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
