title: Shreshth Khilani
email: shreshth.khilani@gmail.com
description: >
  This is Shreshth's theatre portfolio; 
  I like to believe that I'm a theatre artist and a web developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shreshthkhilani.com"
twitter_username: shreshthkhilani
github_username:  shreshthkhilani

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
